bookstore/books/urls.py
# wlp
from django.conf.urls import url

from books import views

urlpatterns = [
    url(r'^$', views.index, name='index'), # 首页

#     详情页
    url(r'books/(?P<books_id>\d+)/$', views.detail, name='detail'),

#     列表页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$', views.list, name='list'),
]

bookstore/bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # 用户模块
    url(r'^user/', include('users.urls', namespace='user')),
    # 富文本编辑器
    url(r'^tinymce/', include('tinymce.urls')),
    # 商品模块
    url(r'^', include('books.urls', namespace='books')),
#     购物车模块
    url(r'^cart/', include('cart.urls', namespace='cart')),
# 订单模块
	url(r'^order/', include('order.urls', namespace='order')),
#     评论模块
    url(r'^comment/', include('comments.urls', namespace='comment')),

    url(r'^search/',include('haystack.urls')),

]

bookstore/cart/urls.py
from django.conf.urls import url

from cart import views

urlpatterns = [
	# 添加购物车数据
	url(r'^add/$', views.cart_add, name='add'),

	# 获取用户购物车中商品的数量
	url(r'^count/$', views.cart_count, name='count'),

	# 显示购物车页面
	url(r'^$', views.cart_show, name='show'),

	# 购物车商品记录删除
	url(r'^del/$', views.cart_del, name='delete'),

]


# wlp

bookstore/users/urls.py
from django.conf.urls import url

from users import views

urlpatterns = [
	# 用户注册
	url(r'^register/$', views.register, name='register'),

	# 注册页面表单提交
	url(r'^register_handle/$', views.register_handle, name='register_handle'),

	# 显示登录页面
	url(r'^login/$', views.login, name='login'),

	#用户登录校验
	url(r'^login_check/$', views.login_check, name='login_check'),

# 	用户退出登录
	url(r'^logout/$', views.logout, name='logout'),

# 	用户中心订单页
	url(r'^order/$', views.order, name='order'),

	# 用户中心-信息页
	url(r'^$', views.user, name='user'),

# 	用户中心地址页
	url(r'^address/$', views.address, name='address'),

# 	验证码功能
	url(r'^verifycode/$', views.veriycode, name='verifycode'),
# 用户激活
	url(r'^active/(?P<token>.*)/$', views.register_active, name='active'),



]

bookstore/users/models.py
# coding:utf-8
from django.db import models

from db.base_model import BaseModel

from utils import get_hash


# Create your models here.


# 实现添加和查找账户信息的功能
class PassportManger(models.Manager):
    def add_one_passport(self, username, password, email):
        # 添加一个账户信息
        passport = self.create(username=username, password=get_hash(password), email=email)
        return passport

    def get_one_passport(self, username, password):
        # 根据用户名和密码查找账户的信息
        try:
            passport = self.get(username=username, password=get_hash(password))
        except self.model.DoesNotExist:

            # 账户不存在
            passport = None
        return passport

    def check_passport(self,username):
        try:
            passport = self.get(username=username)

        except self.model.DoesNotExist:
            passport = None

        # if passport:
        #     return True
		#
        # return False
        return passport





# 针对Users设计一张表
class Passport(BaseModel):
    # 用户模型类
    username = models.CharField(max_length=20, verbose_name='用户名称')
    password = models.CharField(max_length=40, verbose_name='用户密码')
    email = models.EmailField(verbose_name='用户邮箱')
    is_active = models.BooleanField(default=False, verbose_name='激活状态')

    # 用户表的管理器
    objects = PassportManger()

    class Meta:
        db_table = 's_user_account'



# 对函数抽象
class AddressManager(models.Manager):
    # 地址模型类管理器类
    def get_default_address(self,passport_id):
        # 查询指定用户的莫认收货地址
        try:
            addr = self.get(passport_id=passport_id,is_default=True)

        except self.model.DoesNotExist:
            # 没有默认的收货地址
            addr = None

        return addr


    def add_one_address(self,passport_id,recipient_name,recipient_addr,zip_code,recipient_phone):
        # 添加收货地址

        # 判断用户是否有默认收货地址
        addr = self.get_default_address(passport_id=passport_id)

        if addr:
            # 存在默认地址
            is_default = False

        else:
            # 不存在默认地址
            is_default = True
        # 添加一个地址
        addr = self.create(
            passport_id = passport_id,
            recipient_name = recipient_name,
            recipient_addr = recipient_addr,
            zip_code = zip_code,
            recipient_phone = recipient_phone,
            is_default=is_default
        )

        return addr


# 用户中心的实现
class Address(BaseModel):
    # 地址模型类
    recipient_name = models.CharField(max_length=20,verbose_name='收件人')
    recipient_addr = models.CharField(max_length=256,verbose_name='收件地址')
    zip_code = models.CharField(max_length=6,verbose_name='邮政编码')
    recipient_phone = models.CharField(max_length=11,verbose_name='联系电话')
    is_default = models.BooleanField(default=False,verbose_name='是否默认')
    passport = models.ForeignKey('Passport',verbose_name='账户')

    objects = AddressManager()

    class Meta:
        db_table = 's_user_address'

bookstore/users/views.py
import re

from django.conf import settings
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render,redirect
from django_redis import get_redis_connection
from itsdangerous import SignatureExpired
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

from books.models import Books
from order.models import OrderInfo,OrderGoods
from users.models import Address
from users.models import Passport
from utils.decorators import login_required


# Create your views here.

# 用户注册处理
def register_handle(requst):
	username = requst.POST.get('user_name')
	password = requst.POST.get('pwd')
	email = requst.POST.get('email')

	if not all([username,password,email]):
		return render(requst,'users/register.html',{'errmsg':'参数不能为空'})

	if not re.match(r'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$',email):
		return render(requst,'users/register.html',{'errmsg':'邮箱不合法'})

	p = Passport.objects.check_passport(username=username)

	if p:
		return render(requst,'users/register.html',{'errmsg':'用户名已存在'})

	passport = Passport.objects.add_one_passport(username=username,password=password,email=email)
	serializer = Serializer(settings.SECRET_KEY, 3600)
	token = serializer.dumps({'confirm': passport.id})  # 返回bytes
	token = token.decode()

	# send_active_email.delay(token, username, email)

	# send_mail('尚硅谷书城用户激活','','settings.EMAIL_FROM',[email],html_message='<a href="http://127.0.0.:8000/user/active/%s/">http://127.0.0.1:8000/user/active/</a>' % token)
	send_mail('尚硅谷书城用户激活', '', settings.EMAIL_FROM, [email],html_message='<a href="http://127.0.0.1:8000/user/active/%s/">http://127.0.0.1:8000/user/active/</a>' % token)


	return redirect(reverse('books:index'))

# 用户中心地址页
@login_required
def address(request):
	# 获取登录用户的id
	passport_id = request.session.get('passport_id')

	if request.method == 'GET':
		# 显示地址页面
		# 查询用户的默认地址
		addr = Address.objects.get_default_address(passport_id=passport_id)
		return render(request,'users/user_center_site.html',{'addr':addr,'page':'address'})

	else:
		# 添加收货地址
		# 接收数据
		recipient_name = request.POST.get('username')
		recipient_addr = request.POST.get('addr')
		zip_code = request.POST.get('zip_code')
		recipient_phone = request.POST.get('phone')
		#进行校验
		if not all([recipient_name,recipient_addr,zip_code,recipient_phone]):
			return render(request,'users/user_center_site.html',{'errmsg':'参数不必为空'})
		# 添加收货地址
		Address.objects.add_one_address(passport_id=passport_id,
										recipient_name=recipient_name,
										recipient_addr=recipient_addr,
										zip_code=zip_code,
										recipient_phone=recipient_phone)
		#返回应答
		return redirect(reverse('user:address'))

@login_required
# 用户中心信息页
def user(request):
	passport_id = request.session.get('passport_id')
	addr = Address.objects.get_default_address(passport_id=passport_id)
	con = get_redis_connection('default')
	key = 'history_%d' % passport_id

	books_li = []

	for id in books_li:
		books = Books.objects.get_books_by_id(books_id=id)
		books_li.append(books)


	return render(request,'users/user_center_info.html',{
		'addr':addr,
        'page':'user',
        'books_li':books_li
	})


def logout(request):
	request.session.flush()
	return redirect(reverse('books:index'))



def login_check(request):
	# 用户登录校验
	#  获取数据
	username = request.POST.get('username')
	password = request.POST.get('password')
	remember = request.POST.get('remember')
	# veriycode = request.POST.get('veriycode')
	verifycode = request.POST.get('verifycode')
	#     数据校验
	if not all([username,password,remember,veriycode]):
		print(111)
		print(username)
		print(password)
		print(remember)
		print(veriycode)
		return JsonResponse({'res':2})

	if verifycode.upper() != request.session['verifycode']:
		return JsonResponse({'res': 2})

	passport = Passport.objects.get_one_passport(username=username,password=password)

	if passport:
		next_url =reverse('books:index')
		jres = JsonResponse({'res':1,'next_url':next_url})

		if remember == 'true':
			jres.set_cookie('username',username,max_age=7*24*3600)

		else:
			jres.delete_cookie('username')

		request.session['islogin'] = True
		request.session['username'] = username
		request.session['passport_id'] = passport.id
		return jres

	else:
		return JsonResponse({'res':0})

def login(request):
	# 显示登录页面
	username = ''
	checked = ''
	context = {
        'username':username,
        'checked':checked,
	}

	return render(request,'users/login.html',context)

def register(request):
	# 显示用户注册页面
	return render(request, 'users/register.html')



# 用户中心订单页
@login_required
def order(request):
	passport_id = request.session.get('passport_id')
	order_li = OrderInfo.objects.filter(passport_id=passport_id)
	for order in order_li:
		order_id = order.order_id
		order_books_li = OrderGoods.objects.filter(order_id=order_id)
		for order_books in order_books_li:
			count = order_books.count
			price = order_books.price
			amount = count * price
			order_books.amount = amount

		order.order_books_li = order_books_li

	context = {
        'order_li':order_li,
        'page':'order'
	}
	return render(request, 'users/user_center_order.html', context)




# 登录验证码
def veriycode(request):
	from PIL import Image,ImageDraw,ImageFont
	import random
	bgcolor = (random.randrange(20,100),random.randrange(
		20,100
	),255)
	width = 100
	height = 25
	im = Image.new('RGB',(width,height),bgcolor)
	draw = ImageDraw.Draw(im)
	for i in range(0,100):
		xy = (random.randrange(0,width),random.randrange(0,height))
		fill = (random.randrange(0,255),255,random.randrange(0,255))
		draw.point(xy,fill=fill)

	str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
	rand_str = ''
	for i in range(0,4):
		rand_str += str1[random.randrange(0,len(str1))]

	font = ImageFont.truetype('/usr/share/fonts/truetype/fonts-japanese-gothic.ttf',15)
	fontcolor = (255,random.randrange(0,255),random.randrange(0,255))

	draw.text((5,2),rand_str[0],font=font,fill=fontcolor)
	draw.text((25,2),rand_str[1],font=font,fill=fontcolor)
	draw.text((50,2),rand_str[2],font=font,fill=fontcolor)
	draw.text((75,2),rand_str[3],font=font,fill=fontcolor)

	del draw

	request.session['verifycode'] = rand_str

	import io
	buf = io.BytesIO()
	im.save(buf,'png')

	return HttpResponse(buf.getvalue(),'image/png')

# 用户激活功能的实现
def register_active(request, token):
	'''用户账户激活'''
	serializer = Serializer(settings.SECRET_KEY, 3600)
	try:
		info = serializer.loads(token)
		passport_id = info['confirm']
		passport = Passport.objects.get(id=passport_id)
		passport.is_active = True
		passport.save()

		return redirect(reverse('user:login'))

	except SignatureExpired:
		return HttpResponse('激活链接已过期')

bookstore/templates/users/login.html
{#登录页面#}

{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-登录{% endblock title %}
{% block topfiles %}
<script>
    $(function () {
        $('#btnLogin').click(function () {

{#             获取用户名和密码#}
            username = $('#username').val()
            password = $('#pwd').val()
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            remember = $('input[name="remember"]').prop('checked')
            vc = $('input[name="vc"]').val()
{#             发起ajax请求#}
            params = {
                'username': username,
                'password': password,
                'csrfmiddlewaretoken': csrf,
                'remember': remember,
                'verifycode': vc,
            }

            console.log('params:',params)


            $.post('/user/login_check/', params, function (data) {

                console.log('data:',data)

                if (data.res == 0){
                    $('#username').next().html('用户名或密码错误').show()
                }
                else
                {
{#                     跳转页面#}
                    location.href = data.next_url
                }
            })
        })
    })
</script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}

    <div class="login_top clearfix">
        <a href="/bookstore/templates/books/index.html" class="login_logo"><img src="{% static 'images/logo.png' %}" style="width: 160px; height: 53px;"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">学计算机 · 来尚硅谷</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="#">立即注册</a>
                </div>
                <div class="form_input">
                    {% csrf_token %}
                    <input type="text" id="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
                    <div class="user_error">输入错误</div>

                    <input type="password" id="pwd" class="pass_input" placeholder="请输入密码">
                    <div class="pwd_error">输入错误</div>

                    <div style="top: 230px;position: absolute;">
                        <input type="text" id="vc" name="vc">
                        <img id="verifycode" src="/user/verifycode/" alt="CheckCode"/>
                    </div>

                    <div class="more_input clearfix">
                        <input type="checkbox" name="remember" {{ checked }}>
                        <label>记住用户名</label>
                        <a href="#">忘记密码</a>
                    </div>
                    <input type="button" id="btnLogin" value="登录" class="input_submit">

                </div>
            </div>
        </div>
    </div>
{% endblock body %}




bookstore/templates/users/register.html
{#注册页面#}
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-注册{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <a class="reg_logo"><img src="/bookstore/static/images/logo.png" style="width: 160px; height: 53px;"></a>
            <div class="reg_slogan">学计算机  ·  来尚硅谷</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="#">登录</a>
            </div>
            <div class="reg_form clearfix">
                <form method="post" action="/user/register_handle/">
                    {% csrf_token %}
                <ul>
                    <li>
                        <label>用户名:</label>
                        <input type="text" name="user_name" id="user_name">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li>
                        <label>密码:</label>
                        <input type="password" name="pwd" id="pwd">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li>
                        <label>确认密码:</label>
                        <input type="password" name="cpwd" id="cpwd">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li>
                        <label>邮箱:</label>
                        <input type="text" name="email" id="email">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li class="agreement">
                        <input type="checkbox" name="allow" id="allow" checked="checked">
                        <label>同意”尚硅谷书城用户使用协议“</label>
                        <span class="error_tip2">提示信息</span>
                    </li>
                    <li class="reg_sub">
                        <input type="submit" value="注 册" name="">
                        {{errmsg}}
                    </li>
                </ul>
                </form>
            </div>

        </div>

    </div>
{% endblock body %}

bookstore/templates/users/user_center_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-用户中心{% endblock title %}
{% block body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
{#							<li><span>用户名：</span>{{ addr.recipient_name }}</li>#}
                            <li><span>用户名：</span>{{ request.session.username }}</li>
                            {% if addr %}
							<li><span>联系方式：</span>{{ addr.recipient_phone }}</li>
							<li><span>联系地址：</span>{{ addr.recipient_addr}}</li>
                            {% else %}
                            <li><span>联系方式</span>无</li>
                                <li><span>联系地址</span>无</li>
                            {% endif %}
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
                <div class="has_view_list">
                    <ul class="book_type_list clearfix">
                        {% for books in books_li %}
                            <li>
                                <a href="{% url 'books:detail' books_id=books.id %}"><img src="{% static books.image %}"></a>
                                <h4><a href="{% url 'books:detail' books_id=books.id %}">{{ books.name }}</a></h4>
                                <div class="operate">
                                    <span class="price">￥{{ books.price }}</span>
                                    <span class="unit">{{ books.unit }}</span>
                                    <a href="#" class="add_books" title="加入购物车"></a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
		</div>
	</div>

{% endblock body %}

bookstore/templates/users/user_center_order.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
            {% csrf_token %}
				<h3 class="common_title2">全部订单</h3>

            {% for order in order_li %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create_time }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
					<li class="col02 stress">{{ order.status }}</li>
				</ul>

			<table class="order_list_table w980">
                    <tbody>
                        <tr>
                            <td width="55%">
                                {% for order_books in order.order_books_li %}
                                <ul class="order_book_list clearfix">
                                    <li class="col01"><img src="{% static order_books.books.image %}"></li>
                                    <li class="col02">{{ order_books.books.name }}<em>{{ order_books.books.price }}元/{{ order_books.books.unit }}</em></li>
                                    <li class="col03">{{ order_books.count }}</li>
                                    <li class="col04">{{ order_books.amount }}元</li>
                                </ul>
                                {% endfor %}
                            </td>
                            <td width="15%">{{ order.total_price }}元</td>
{#                            <td width="15%">{{ order.status | order_status }}</td>#}
                            <td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}" class="oper_btn">去付款</a></td>
                        </tr>
                    </tbody>
                </table>
                {% endfor %}
{% load filters %}
			    <div class="pagenation">
                    <a href="#">上一页</a>
                    <a href="#" class="active">1</a>
                    <a href="#">2</a>
                    <a href="#">3</a>
                    <a href="#">4</a>
                    <a href="#">5</a>
                    <a href="#">下一页></a>
                </div>
        </div>
    </div>

{% endblock body %}

{% block bottomfiles %}

    <script>
    $(function () {
        $('.oper_btn').click(function () {
            order_id = $(this).attr('order_id')
            order_status = $(this).attr('order_status')
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            params = {'oeder_id':order_id,'csrfmiddlewaretoken':csrf}

            if(order_status == 1){

                $.post('/order/pay/',params,function (data) {
                    if (data.res == 3){
                        window.open(data.pay_url)
                        $.post('/order/check_pay/',params,function (data) {
                            if (data.res == 3){
                                alert('支付成功')
                                location.reload()
                            }
                            else {
                                    alert(data.errmsg)
                                }
                        })
                    }
                    else {
                        alert(data.errmsg)
                    }
                })
            }
        })
    })
    </script>

{% endblock bottomfiles %}

bookstore/templates/users/user_center_site.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-用户{% endblock %}
{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="user_center_info.html">· 个人信息</a></li>
				<li><a href="user_center_order.html">· 全部订单</a></li>
				<li><a href="user_center_site.html" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if addr %}
						<dd>{{ addr.recipient_adr }} ({{ addr.recipient_name }}收) {{ addr.recipient_phone }}</dd>
                        {% else %}
                            <dd>无</dd>
                        {% endif %}
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">

                    <form method="post" action="/user/address/">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
	
{% endblock %}