bookstore/books/urls.py
# wlp
from django.conf.urls import url

from books import views

urlpatterns = [
    url(r'^$', views.index, name='index'), # 首页

#     详情页
    url(r'books/(?P<books_id>\d+)/$', views.detail, name='detail'),

#     列表页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$', views.list, name='list'),
]

bookstore/bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # 用户模块
    url(r'^user/', include('users.urls', namespace='user')),
    # 富文本编辑器
    url(r'^tinymce/', include('tinymce.urls')),
    # 商品模块
    url(r'^', include('books.urls', namespace='books')),
#     购物车模块
    url(r'^cart/', include('cart.urls', namespace='cart')),
# 订单模块
	url(r'^order/', include('order.urls', namespace='order')),
#     评论模块
    url(r'^comment/', include('comments.urls', namespace='comment')),

    url(r'^search/',include('haystack.urls')),

]

bookstore/cart/urls.py
from django.conf.urls import url

from cart import views

urlpatterns = [
	# 添加购物车数据
	url(r'^add/$', views.cart_add, name='add'),

	# 获取用户购物车中商品的数量
	url(r'^count/$', views.cart_count, name='count'),

	# 显示购物车页面
	url(r'^$', views.cart_show, name='show'),

	# 购物车商品记录删除
	url(r'^del/$', views.cart_del, name='delete'),

]


# wlp

bookstore/books/models.py
# wlp
from django.db import models
from tinymce.models import HTMLField

from books.enums import *
from db.base_model import BaseModel


# Create your models here.

class BooksManager(models.Manager):
    '''商品模型管理器类'''
    # sort='new' 按照创建时间进行排序
    # sort='hot' 按照商品销量进行排序
    # sort='price' 按照商品的价格进行排序
    # sort= 按照默认顺序排序
    def get_books_by_type(self, type_id, limit=None, sort='default'):
        '''根据商品类型id查询商品信息'''
        if sort == 'new':
            order_by = ('-create_time',)
        elif sort == 'hot':
            order_by = ('-sales', )
        elif sort == 'price':
            order_by = ('price', )
        else:
            order_by = ('-pk', ) # 按照primary key降序排列。

        # 查询数据
        books_li = self.filter(type_id=type_id).order_by(*order_by)

        # 查询结果集的限制
        if limit:
            books_li = books_li[:limit]
        return books_li

    def get_books_by_id(self, books_id):
        '''根据商品的id获取商品信息'''
        try:
            books = self.get(id=books_id)
        except self.model.DoesNotExist:
            # 不存在商品信息
            books = None
        return books

class Books(BaseModel):
    '''商品模型类'''
    books_type_choices = ((k, v) for k,v in BOOKS_TYPE.items())
    status_choices = ((k, v) for k,v in STATUS_CHOICE.items())
    type_id = models.SmallIntegerField(default=PYTHON, choices=books_type_choices, verbose_name='商品种类')
    name = models.CharField(max_length=20, verbose_name='商品名称')
    desc = models.CharField(max_length=128, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    unite = models.CharField(max_length=20, verbose_name='商品单位')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    detail = HTMLField(verbose_name='商品详情')
    image = models.ImageField(upload_to='books', verbose_name='商品图片')
    status = models.SmallIntegerField(default=ONLINE, choices=status_choices, verbose_name='商品状态')

    objects = BooksManager()

    class Meta:
        db_table = 's_books'

bookstore/books/views.py
# wlp

from django.core.paginator import  Paginator
from django.core.urlresolvers import reverse
from django.shortcuts import render,redirect
from django.views.decorators.cache import cache_page
from django_redis import get_redis_connection

from books.enums import *
from books.models import Books


# Create your views here.

# 商品种类  页码  排序方式
def list(request,type_id,page):
    # 商品列表页面

    # 获取排序方式
    sort = request.GET.get('sort','default')

# 判断type——id是否合法
    if int(type_id) not in BOOKS_TYPE.keys():
        return redirect(reverse('books:index'))
# 根据商品种类id和排序方式查询数据
    books_li = Books.objects.get_books_by_type(type_id=type_id,sort=sort)

    # 分页
    paginator = Paginator(books_li,1)

    # 获取分页之后的总页数
    num_pages = paginator.num_pages

    # 取第page页数据
    if page == '' or int(page) > num_pages:
        page = 1

    else:
        page = int(page)

# 返回值是一个page类的实例对象
    books_li = paginator.page(page)

# 进行页码控制

    # 总页数小于5,显示所有页码
    if num_pages < 5:
        pages = range(1,num_pages+1)

# 当前页码是前3页，显示1-5页
    elif page <= 3:
        pages = range(1,6)

# 当前页是后3页，显示后5页
    elif num_pages - page <= 2:
        pages = range(num_pages-4,num_pages+1)

# 其他情况，显示当前页前2页，后两页，当前页
    else:
        pages = range(page-2,page+3)

# 新品推荐
    books_new = Books.objects.get_books_by_type(type_id=type_id,limit=2,sort='new')

# 定义上下文
    type_title = BOOKS_TYPE[int(type_id)]
    context = {
        'books_li':books_li,
        'books_new':books_new,
        'type_id':type_id,
        'sort':sort,
        'type_title':type_title,
        'pages':pages
    }

# 使用模板
    return render(request,'books/list.html',context)


# def detail(request,books_id):
#     books = Books.objects.get_books_by_id(books_id=books_id)
#
#     if books is None:
#         return redirect(reverse('books:index'))
#
#     books_li = Books.objects.get_books_by_type(type_id=books_id,limit=2,sort='new')
#
#     context = {'books':books,'books_li':books_li}
#
#     return render(request,'books/detail.html',context)

def detail(request, books_id):
    '''显示商品的详情页面'''
    # 获取商品的详情信息
    books = Books.objects.get_books_by_id(books_id=books_id)

    if books is None:
        # 商品不存在，跳转到首页
        return redirect(reverse('books:index'))

    # 新品推荐
    books_li = Books.objects.get_books_by_type(type_id=books.type_id, limit=2, sort='new')

    # 用户登录之后，才记录浏览记录
    # 每个用户浏览记录对应redis中的一条信息 格式:'history_用户id':[10,9,2,3,4]
    # [9, 10, 2, 3, 4]
    if request.session.has_key('islogin'):
        # 用户已登录，记录浏览记录
        con = get_redis_connection('default')
        key = 'history_%d' % request.session.get('passport_id')
        # 先从redis列表中移除books.id
        con.lrem(key, 0, books.id)
        con.lpush(key, books.id)
        # 保存用户最近浏览的5个商品
        con.ltrim(key, 0, 4)

    # 定义上下文
    context = {'books': books, 'books_li': books_li}

    # 使用模板
    return render(request, 'books/detail.html', context)



@cache_page(60 * 15)
def index(request):

    # 显示首页
    # 查询每个种类的3个新品信息和4个销量最好的商品信息
    python_new = Books.objects.get_books_by_type(PYTHON,3,sort='new')
    python_hot = Books.objects.get_books_by_type(PYTHON,4,sort='hot')
    javascript_new = Books.objects.get_books_by_type(JAVASCRIPT,3,sort='new')
    javascript_hot = Books.objects.get_books_by_type(JAVASCRIPT,4,sort='hot')
    algorithms_new = Books.objects.get_books_by_type(ALGORITHMS,3,sort='new')
    algorithms_hot = Books.objects.get_books_by_type(ALGORITHMS,4,sort='hot')
    machinelearning_new = Books.objects.get_books_by_type(MACHINELEARNING,3,sort='new')
    machinelearning_hot = Books.objects.get_books_by_type(MACHINELEARNING,4,sort='hot')
    operatingsystem_new = Books.objects.get_books_by_type(OPERATINGSYSTEM,3,sort='new')
    operatingsystem_hot = Books.objects.get_books_by_type(OPERATINGSYSTEM,4,sort='hot')
    database_new = Books.objects.get_books_by_type(DATABASE,3,sort='new')
    database_hot = Books.objects.get_books_by_type(DATABASE,4,sort='hot')

    # 定义模板的上下文
    context = {
        'python_new':python_new,
        'python_hot':python_hot,
        'javascript_new':javascript_new,
        'javascript_hot':javascript_hot,
        'algorithms_new':algorithms_new,
        'algorithms_hot':algorithms_hot,
        'machinelearning_new':machinelearning_new,
        'machinelearning_hot':machinelearning_hot,
        'operatingsystem_new':operatingsystem_new,
        'operatingsystem_hot':operatingsystem_hot,
        'database_new':database_new,
        'database_hot':database_hot,
    }

    return render(request, 'books/index.html',context)

bookstore/templates/books/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷{% endblock title %}
{% block topfiles %}
<script>
$(function () {
    update_total_price()
{#     计算总价#}
    function update_total_price() {
{#         获取商品的价格和数量#}
        books_price = $('.show_pirze').children('em').text()
        books_count = $('.num_show').val()
{#         计算商品的总价#}
        books_price = parseFloat(books_price)
        books_count = parseInt(books_count)
        total_price = books_price * books_count
{#         设置商品总价#}
        $('.total').children('em').text(total_price.toFixed(2) + '元')
    }
{#    商品增加#}
    $('.add').click(function () {
{#         获取商品的数量#}
        books_count = $('.num_show').val()
{#         加1#}
        books_count = parseInt(books_count) + 1
{#         重新设置值#}
        $('.num_show').val(books_count)
{#         计算总价#}
        update_total_price()
    })
{#     商品减少#}
    $('.minus').click(function () {
{#         获取商品的数量#}
        books_count = $('.num_show').val()
{#         加1#}
        books_count = parseInt(books_count) - 1
        if (books_count == 0){
            books_count = 1
        }
{#         重新设置值#}
        $('.num_show').val(books_count)
        // 计算总价
        update_total_price()
    })
{#     手动输入#}
    $('.num_show').blur(function () {
{#         获取商品的数量#}
        books_count = $(this).val()
{#         数据校验#}
        if (isNaN(books_count) || books_count.trim().length == 0 || parseInt(books_count) <= 0 ){
            books_count = 1
        }
{#         重新设置值#}
        $('.num_show').val(parseInt(books_count))
{#        计算总价#}
        update_total_price()
    })
})
</script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="python">Python</a></li>
					<li><a href="#" class="javascript">Javascript</a></li>
					<li><a href="#" class="algorithms">数据结构与算法</a></li>
					<li><a href="#" class="machinelearning">机器学习</a></li>
					<li><a href="#" class="operatingsystem">操作系统</a></li>
					<li><a href="#" class="database">数据库</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">Python</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="book_detail_con clearfix">
		<div class="book_detail_pic fl"><img src="{% static books.image %}"></div>

		<div class="book_detail_list fr">
			<h3>{{ books.name }}</h3>
			<p>{{ books.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ books.price }}</em></span>
				<span class="show_unit">单  位：{{ books.unit }}</span>
			</div>
			<div class="book_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em>100元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" books_id="{{ books.id }}" class="add_cart" id="add_cart">加入购物车</a>
				<a href="#" id="write-comment" class="comment">我要写评论</a>
			</div>
			<div style="display:flex;" id="comment-input" data-bookid="{{ books.id }}" data-userid="{{ request.session.passport_id }}">
			  <div>
			    <input type="text" placeholder="评论内容">
			  </div>
			  <div id="submit-comment">
			    <button>
			      提交评论
			    </button>
			  </div>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_book">
				<h3>新品推荐</h3>
				<ul>
                    {% for book in books_li %}
					<li>
						<a href="{% url 'books:detail' books_id=books.id %}"><img src="{% static book.image %}"></a>
						<h4><a href="{% url 'books:detail' books_id=books.id %}">{{ book.name }}</a></h4>
						<div class="prize">￥{{ book.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active" id="detail">商品介绍</li>
				<li id="comment">评论</li>
			</ul>

			<div class="tab_content">
				<dl id="book_detail">
					<dt>商品详情：</dt>
					<dd>{{ books.detail | safe }}</dd>
				</dl>
				<dl id="book_comment">
				</dl>
			</div>

		</div>
	</div>
	<div class="add_jump"></div>
{% endblock body %}
{% block bottomfiles %}
<script type="text/javascript">
	var $add_x = $('#add_cart').offset().top;
	var $add_y = $('#add_cart').offset().left;
	var $to_x = $('#show_count').offset().top;
	var $to_y = $('#show_count').offset().left;
	$('#comment-input').hide()
	$('#add_cart').click(function(){
{#         获取商品的id和商品数量#}
        books_id = $(this).attr('books_id')
        books_count = $('.num_show').val()
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
{#         发起请求，访问/cart/add/, 进行购物车数据的添加#}
        params = {
        	'books_id': books_id,
        	'books_count': books_count,
            'csrfmiddlewaretoken': csrf
        }
        $.post('/cart/add/', params, function (data) {
            if (data.res == 5){
{#                添加成功#}
                $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                $(".add_jump").stop().animate({
                    'left': $to_y+7,
                    'top': $to_x+7},
                    "fast", function() {
                        $(".add_jump").fadeOut('fast',function(){
{#                             获取原有show_count的值#}
                            count = $('#show_count').html()
                            count = parseInt(count) + parseInt(books_count)
                            $('#show_count').html(count);
                        });
                });
            }
            else {
{#                 添加失败#}
                alert(data.errmsg)
            }
        })
	})


{#	 提交评论----获取评论#}
	$.ajax({
		url: '/comment/comment/' + $('#comment-input').data('bookid'),
		success: function (res) {
			if (res.code === 200) {
				var data = res.data;
				console.log(data);
				var div_head = '<div>';
				var div_tail = '</div>';
				var dom_element = ''
				for(i = 0; i < data.length; i++) {
					var head = '<div>';
					var tail = '</div>';
					var temp = head + '<span>' + data[i].user_id + '</span>' + '<br>' + '<span>' + data[i].content + '</span>';
					dom_element += temp;
				}
				dom_element = div_head + dom_element + div_tail;
				$('#book_comment').append(dom_element);
			}
		}
	})
	$('#detail').click(function () {
		$(this).addClass('active');
		$('#comment').removeClass('active');
		$('#book_comment').hide();
		$('#book_detail').show();
	})
	$('#comment').click(function () {
		$(this).addClass('active');
		$('#detail').removeClass('active');
		$('#book_comment').show();
		$('#book_detail').hide();
	})
	$('#write-comment').click(function () {
		$('#comment-input').show();
	})
	$('#submit-comment').click(function () {
		var book_id = $('#comment-input').data('bookid');
		var user_id = $('#comment-input').data('userid');
		var content = $('#comment-input input').val();

		var data = {
			book_id: book_id,
			user_id: user_id,
			content: content,
		}
		console.log('content: ', content);
		$.ajax({
			type: 'POST',
			url: '/comment/comment/' + book_id + '/',
			data: JSON.stringify(data),
			success: function (res) {
				if (res.code === 200) {
					$('#comment-input').hide();
				}
			}
		})
	})
</script>


{#提交评论的样式#}
<style type="text/css">
.comment {
	background-color: #c40000;
	color: #fff;
	margin-left: 10px;
	position: relative;
	z-index: 10;
	display: inline-block;
	width: 178px;
	height: 38px;
	border: 1px solid #c40000;
	font-size: 14px;
	line-height: 38px;
	text-align: center;
}
</style>
{% endblock bottomfiles %}



bookstore/templates/books/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}

{% block body %}

    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">移动端书城</a></li>
                <li class="interval">|</li>
                <li><a href="">秒杀</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">

        <ul class="subnav fl">
            <li><a href="#model01" class="python">Python</a></li>
            <li><a href="#model02" class="javascript">Javascript</a></li>
            <li><a href="#model03" class="algorithms">数据结构与算法</a></li>
            <li><a href="#model04" class="machinelearning">机器学习</a></li>
            <li><a href="#model05" class="operatingsystem">操作系统</a></li>
            <li><a href="#model06" class="database">数据库</a></li>
        </ul>

        <div class="slide fl">
            <ul class="slide_pics">
                <li><img src="{% static 'images/slide.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
                <li><img src="{% static 'images/slide02.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
                <li><img src="{% static 'images/slide03.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
                <li><img src="{% static 'images/slide04.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>

        <div class="adv fl">
            <a href="#"><img src="{% static 'images/adv01.jpg' %}" style="width: 240px; height: 135px;"></a>
            <a href="#"><img src="{% static 'images/adv02.jpg' %}" style="width: 240px; height: 135px;"></a>
        </div>

    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model01">Python</h3>
            <div class="subtitle fl">
                <span>|</span>
                {% for book in python_new %}
                    <a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a>
                    <a href="">{{ book.name }}</a>
                {% endfor %}
            </div>
            <a href="{% url 'books:list' type_id=1 page=1 %}" class="book_more fr">查看更多 ></a>
        </div>
        <div class="book_con clearfix">
            <div class="book_banner fl"><img src="{% static 'images/banner01.jpg' %}"></div>
            <ul class="book_list fl">
                {% for book in python_hot %}
                <li>
                    <h4><a href="{% url 'books:detail' books_id=book.id  %}">{{ book.name }}</a></h4>
                    <a href="{% url 'books:detail' books_id=book.id  %}"><img src="{% static book.image %}"></a>
                    <div class="prize">¥ {{ book.price }}</div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model02">Javascript</h3>
            <div class="subtitle fl">
                <span>|</span>
                {% for book in javascript_new %}
                    <a href="{% url 'books:list' type_id=1 page=1 %}">{{ book.name }}</a>
                    <a href="">{{ book.name }}</a>
                {% endfor %}
            </div>
            <a href="{% url 'books:list' type_id=1 page=1 %}" class="book_more fr">查看更多 ></a>
        </div>
        <div class="book_con clearfix">
            <div class="book_banner fl"><img src="{% static 'images/banner02.jpg' %}"></div>
            <ul class="book_list fl">
                {% for book in javascript_hot %}
                <li>
                    <h4><a href="#">{{ book.name }}</a></h4>
                    <a href="#"><img src="{% static book.image %}">{{ book.name }}</a>
                    <div class="prize">¥ {{ book.price }}</div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model03">数据结构与算法</h3>
            <div class="subtitle fl">
                <span>|</span>
                {% for book in algorithms_new %}
                    <a href="{% url 'books:list' type_id=1 page=1 %}">{{ book.name }}</a>
                    <a href="">{{ book.name }}</a>
                {% endfor %}
            </div>
            <a href="{% url 'books:list' type_id=1 page=1 %}" class="book_more fr">查看更多 ></a>
        </div>

        <div class="book_con clearfix">
            <div class="book_banner fl"><img src="{% static 'images/banner03.jpg' %}"></div>
            <ul class="book_list fl">
                {% for book in algorithms_hot %}
                <li>
                    <h4><a href="{% url 'books:list' type_id=1 page=1 %}">{{ book.name }}</a></h4>
                    <a href="{% url 'books:list' type_id=1 page=1 %}"><img src="{% static book.image %}"></a>
                    <div class="prize">¥ {{ book.price }}</div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model04">机器学习</h3>
            <div class="subtitle fl">
                <span>|</span>
                {% for book in machinelearning_new %}
                    <a href="#">{{ book.name }}</a>
                {% endfor %}pppp
            </div>
            <a href="{% url 'books:list' type_id=1 page=1 %}" class="book_more fr">查看更多 ></a>
        </div>

        <div class="book_con clearfix">
            <div class="book_banner fl"><img src="{% static 'images/banner04.jpg' %}"></div>
            <ul class="book_list fl">
                {% for book in machinelearning_hot %}
                <li>
                    <h4><a href="#">{{ book.name }}</a></h4>
                    <a href="#"><img src="{% static book.image %}"></a>
                    <div class="prize">¥ {{ book.price }}</div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model05">操作系统</h3>
            <div class="subtitle fl">
                <span>|</span>
                {% for book in operatingsystem_new %}
                    <a href="#">{{ book.name }}</a>
                {% endfor %}
            </div>
            <a href="#" class="book_more fr">查看更多 ></a>
        </div>

        <div class="book_con clearfix">
            <div class="book_banner fl"><img src="{% static 'images/banner05.jpg' %}"></div>
            <ul class="book_list fl">
                {% for book in operatingsystem_hot %}
                <li>
                    <h4><a href="#">{{ book.name }}</a></h4>
                    <a href="#"><img src="{% static book.image %}"></a>
                    <div class="prize">¥ {{ book.price }}</div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model06">数据库</h3>
            <div class="subtitle fl">
                <span>|</span>
                {% for book in database_new %}
                    <a href="#">{{ book.name }}</a>
                {% endfor %}
            </div>
            <a href="#" class="book_more fr">查看更多 ></a>
        </div>

        <div class="book_con clearfix">
            <div class="book_banner fl"><img src="{% static 'images/banner06.jpg' %}"></div>
            <ul class="book_list fl">
                {% for book in database_hot %}
                <li>
                    <h4><a href="#">{{ book.name }}</a></h4>
                    <a href="#"><img src="{% static book.image %}"></a>
                    <div class="prize">¥ {{ book.price }}</div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock body %}

bookstore/templates/books/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="python">Python</a></li>
					<li><a href="#" class="javascript">Javascript</a></li>
					<li><a href="#" class="algorithms">数据结构与算法</a></li>
					<li><a href="#" class="machinelearning">机器学习</a></li>
					<li><a href="#" class="operatingsystem">操作系统</a></li>
					<li><a href="#" class="database">数据库</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">Python</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_book">
				<h3>新品推荐</h3>
				<ul>
{#                新品推荐 #}
					{% for book in books_new %}
                    <li>
                        <a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
                        <h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
                        <div class="prize">￥{{ book.price }}</div>
                    </li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
{#            按照不同特征排序#}
				<a href="/list/{{ type_id }}/1/" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
                <a href="/list/{{ type_id }}/1/?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
                <a href="/list/{{ type_id }}/1/?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="book_type_list clearfix">
                {#            商品列表#}
				{% for books in books_li %}
                    <li>
                        <a href="{% url 'books:detail' books_id=books.id %}"><img src="{% static books.image %}"></a>
                        <h4><a href="{% url 'books:detail' books_id=books.id %}">{{ books.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ books.price }}</span>
                            <span class="unit">{{ books.unite }}</span>
                            <a href="#" class="add_books" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
			</ul>
            {#前端分页功能的实现#}
			<div class="pagenation">
				{% if books_li.has_previous %}
                    <a href="/list/{{ type_id }}/{{ books_li.previous_page_number }}/?sort={{ sort }}">上一页</a>
                {% endif %}

                {% for pindex in pages %}
                    {% if pindex == books_li.number %}
                        <a href="/list/{{ type_id }}/{{ pindex }}/?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="/list/{{ type_id }}/{{ pindex }}/?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}

                {% if books_li.has_next %}
                    <a href="/list/{{ type_id }}/{{ books_li.next_page_number }}/?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>

{% endblock body %}