bookstore/bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # 用户模块
    url(r'^user/', include('users.urls', namespace='user')),
    # 富文本编辑器
    url(r'^tinymce/', include('tinymce.urls')),
    # 商品模块
    url(r'^', include('books.urls', namespace='books')),
#     购物车模块
    url(r'^cart/', include('cart.urls', namespace='cart')),
# 订单模块
	url(r'^order/', include('order.urls', namespace='order')),
#     评论模块
    url(r'^comment/', include('comments.urls', namespace='comment')),

    url(r'^search/',include('haystack.urls')),

]

bookstore/cart/urls.py
from django.conf.urls import url

from cart import views

urlpatterns = [
	# 添加购物车数据
	url(r'^add/$', views.cart_add, name='add'),

	# 获取用户购物车中商品的数量
	url(r'^count/$', views.cart_count, name='count'),

	# 显示购物车页面
	url(r'^$', views.cart_show, name='show'),

	# 购物车商品记录删除
	url(r'^del/$', views.cart_del, name='delete'),

]


# wlp

bookstore/order/urls.py
from django.conf.urls import url

from order import views

urlpatterns = [
# 	 提交订单页面
	url(r'^place/$', views.order_place, name='place'),

# 	生成订单
	url(r'^commit/$', views.order_commit, name='commit'),

# 订单支付
	url(r'^pay/$', views.order_pay, name='pay'),
# 	查询支付结果
	url(r'^check_pay/$', views.check_pay, name='check_pay')
]
# wlp

bookstore/users/urls.py
from django.conf.urls import url

from users import views

urlpatterns = [
	# 用户注册
	url(r'^register/$', views.register, name='register'),

	# 注册页面表单提交
	url(r'^register_handle/$', views.register_handle, name='register_handle'),

	# 显示登录页面
	url(r'^login/$', views.login, name='login'),

	#用户登录校验
	url(r'^login_check/$', views.login_check, name='login_check'),

# 	用户退出登录
	url(r'^logout/$', views.logout, name='logout'),

# 	用户中心订单页
	url(r'^order/$', views.order, name='order'),

	# 用户中心-信息页
	url(r'^$', views.user, name='user'),

# 	用户中心地址页
	url(r'^address/$', views.address, name='address'),

# 	验证码功能
	url(r'^verifycode/$', views.veriycode, name='verifycode'),
# 用户激活
	url(r'^active/(?P<token>.*)/$', views.register_active, name='active'),



]

bookstore/order/models.py
from django.db import models

from db.base_model import BaseModel


# Create your models here.
# wlp

# 订单信息
class OrderInfo(BaseModel):
    # 订单信息模型类

    PAY_METHOD_CHOICES = (
        (1, "货到付款"),
        (2, "微信支付"),
        (3, "支付宝"),
        (4, "银联支付")
    )

    PAY_METHODS_ENUM = {
        "CASH": 1,
        "WEIXIN": 2,
        "ALIPAY": 3,
        "UNIONPAY": 4,
    }

    ORDER_STATUS_CHOICES = (
        (1, "待支付"),
        (2, "待发货"),
        (3, "待收货"),
        (4, "待评价"),
        (5, "已完成"),
    )

    order_id = models.CharField(max_length=64, primary_key=True, verbose_name='订单编号')
    passport = models.ForeignKey('users.Passport', verbose_name='下单账户')
    addr = models.ForeignKey('users.Address', verbose_name='收货地址')
    total_count = models.IntegerField(default=1, verbose_name='商品总数')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品总价')
    transit_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='订单运费')
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHOICES, default=1, verbose_name='支付方式')
    status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES, default=1, verbose_name='订单状态')
    trade_id = models.CharField(max_length=100, unique=True, null=True, blank=True, verbose_name='支付编号')


    class Meta:
        db_table = 's_order_info'



# 商品信息
class OrderGoods(BaseModel):
    # 订单商品模型类
    order = models.ForeignKey('OrderInfo', verbose_name='所属订单')
    books = models.ForeignKey('books.Books', verbose_name='订单商品')
    count = models.IntegerField(default=1, verbose_name='商品数量')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')


    class Meta:
        db_table = 's_order_books'

bookstore/order/views.py
# wlp

import os
import time
from datetime import datetime

from alipay import AliPay
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import render,redirect
from django_redis import get_redis_connection

from books.models import Books
from order.models import OrderInfo,OrderGoods
from users.models import Address
from utils.decorators import login_required


# Create your views here.


# 显示提交订单页面
@login_required
def order_place(request):
	# 接收数据
	books_ids = request.POST.getlist('books_ids')

	# 校验数据
	if not all(books_ids):
		# 跳转到购物车页面
		return redirect(reverse('cart:show'))
	# 用户收货地址
	passport_id = request.session.get('passport_id')
	addr = Address.objects.get_default_address(passport_id=passport_id)

	# 用户要购买的商品信息
	books_li = []
	# 商品的数目和金额
	total_count = 0
	total_price = 0

	conn = get_redis_connection('default')
	cart_key = 'cart_%d' % passport_id

	for id in books_ids:
		# 根据id获取商品信息
		books = Books.objects.get_books_by_id(books_id=id)
		# 从ridis中获取要购买的商品数目
		count = conn.hget(cart_key,id)
		books.count = count

		# 计算商品小计
		amount = int(count) * books.price
		books.amount = amount
		books_li.append(books)

		# 累计计算商品的总数目和总金额
		total_count += int(count)
		total_price += books.amount

	# 商品运费和实际付款金额
	transit_price = 10
	total_pay = total_price + transit_price

	books_ids = ','.join(books_ids)

	# 模板的上下文
	context = {
		'addr':addr,
		'books_li':books_li,
		'total_count':total_count,
		'total_price':total_price,
		'transit_price':transit_price,
		'total_pay':total_pay,
		'books_ids':books_ids,
	}
	# 使用模板
	return render(request,'order/place_order.html',context)


# 订单提交功能
@transaction.atomic
def order_commit(request):
	# 生成订单
	# 验证用户是否登录
	if not request.session.has_key('islogin'):
		return JsonResponse({'res': 0, 'errmsg': '用户未登录'})

	# 接收数据
	addr_id = request.POST.get('addr_id')
	pay_method = request.POST.get('pay_method')
	books_ids = request.POST.get('books_ids')

	# 进行数据校验
	if not all([addr_id, pay_method, books_ids]):
		return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

	try:
		addr = Address.objects.get(id=addr_id)

	except Exception as e:
		# 地址信息出错
		return JsonResponse({'res': 2, 'errmsg': '地址信息错误'})

	if int(pay_method) not in OrderInfo.PAY_METHODS_ENUM.values():
		return JsonResponse({'res': 3, 'errmsg': '不支持的支付方式'})

	# 订单创建
	# 组织订单信息
	passport_id = request.session.get('passport_id')
	# 订单id+用户的id
	order_id = datetime.now().strftime('%Y%m%d%H%M%S') + str(passport_id)
	#运费
	transit_price = 10
	# 订单商品总数和总金额
	total_count = 0
	total_price = 0

	# 创建一个保存点
	sid = transaction.savepoint()
	try:
		# 向订单信息表中添加一条记录
		order = OrderInfo.objects.create(order_id=order_id,
										 passport_id=passport_id,
										 addr_id=addr_id,
										 total_count=total_count,
										 total_price=total_price,
										 transit_price=transit_price,
										 pay_method=pay_method)

		# 向订单商品表添加订单商品的记录
		books_ids = books_ids.split(',')
		conn = get_redis_connection('default')
		cart_key = 'cart_%d' % passport_id
		# 遍历用户购买的商品信息
		for id in books_ids:
			books = Books.objects.get_books_by_id(books_id=id)
			if books is None:
				transaction.savepoint_rollback(sid)
				return JsonResponse({'res': 4, 'errmsg': '商品信息错误'})

			# 获取用户购买的商品数目
			count = conn.hget(cart_key, id)

			# 判断商品的库存
			if int(count) > books.stock:
				transaction.savepoint_rollback(sid)
				return JsonResponse({'res':5,'errmsg':'商品库存不足'})

			# 创建一条订单商品记录
			OrderGoods.objects.create(
				order_id=order_id,
				books_id=id,
				count=count,
				price=books.price
			)
			# 增加商品的销量,减少商品库存
			books.sales += int(count)
			books.stock -= int(count)
			books.save()

			# 累计计算商品的总数目和总额
			total_count += int(count)
			transit_price += int(count) * books.price
		# 更新订单的商品数目和总金额
		order.total_count = total_count
		order.transit_price = transit_price
		order.save()

	except Exception as e:
		# 操作数据库出错,进行回滚操作
		transaction.savepoint_rollback(sid)
		return JsonResponse({'res':7,'errmsg':'服务器错误'})
	# 清除购物车对应记录
	conn.hdel(cart_key,*books_ids)
	# 事务提交
	transaction.savepoint_commit(sid)
	# 返回应答
	return JsonResponse({'res':6})


# 订单支付
def order_pay(request):
	# 用户判断登录
	if not request.session.has_key('islogin'):
		return JsonResponse({'res':0,'errmsg':'用户未登录'})
	#接收订单id
	order_id = request.POST.get('order_id')
	# 数据校验
	if not order_id:
		return JsonResponse({'res':1,'errmsg':'订单不存在'})

	try:
		order = OrderInfo.objects.get(order_id=order_id,
									  status=1,
									  pay_method=3)

	except OrderInfo.DoesNotExist:
		return JsonResponse({'res':2,'errmsg':'订单信息出错'})

	# 和支付宝进行交互
	alipay = AliPay(
		# 应用id
		appid = '2016090800464054',
		# 默认回调url
		app_notify_url=None,

		app_private_key_path = os.path.join(settings.BASE_DIR,'df_order/app_private_key.pem'),
	# 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥
		alipay_public_key_path = os.path.join(settings.BASE_DIR,'df_order/alipay_public_key.pem'),
		sign_type='RSA2',
		# 默认False
		debug=True,
	)

	# 电脑网站支付，需要跳转到https://openapi.alipaydev.com/gateway.do? + order_string
	total_pay = order.total_price + order.transit_price
	order_string = alipay.api_alipay_trade_page_pay(
		# 订单id
		out_trade_no=order_id,
		total_amount=str(total_pay),
		subject='尚硅谷书城%s' % order_id,
		return_url=None,
		# 可选,不填使用默认notify url
		notify_url=None
	)

	# 返回应答
	pay_url = settings.ALIPAY_URL+'?' + order_string
	return JsonResponse({"res":3,'pay_url':pay_url,'message':'OK'})



# 	获取用户支付的结果
def check_pay(request):
	# 用户判断登录
	if not request.session.has_key('islogin'):
		return JsonResponse({'res':0,'errmsg':'用户未登录'})

	# 订单接收id
	passport_id = request.session.get('passport_id')
	order_id = request.POST.get('order_id')

	# 数据校验
	if not order_id:
		return JsonResponse({'res':1,'errmsg':'订单不存在'})
	try:
		order = OrderInfo.objects.get(order_id=order_id,
									  passport_id=passport_id,
									  pay_method=3)
	except OrderInfo.DoesNotExist:
		return JsonResponse({'res':2,'errmsg':'订单信息出错'})

	# 和支付宝进行交互
	alipay = AliPay(
		appid='2016090800464054',
		app_notify_url = None,
		app_private_key_path=os.path.join(settings.BASE_DIR,'df_order/app_private_key.pem'),
		sign_type='RSA2',
		debug=True,
	)

	while True:
		# 进行支付结果查询
		result = alipay.api_alipay_trade_query(order_id)
		code = result.get('code')
		if code == '10000' and result.get('trade_status') == 'TRADE_SUCCESS':

			# 待发货
			order.status = 2
			# 填写支付宝交易号
			order.trade_id = result.get('trade_no')
			order.save()

			# 返回数据
			return JsonResponse({'res':3,'message':'支付成功'})
		elif code == '40004' or (code == '10000' and result.get('trade_status') == 'WAIT_BUYER_PAY'):
			time.sleep(5)
			continue

		else:
			# 支付出错
			return JsonResponse({'res':4,'errmsg':'支付出错'})

bookstore/templates/order/place_order.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-我的订单{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}

    <h3 class="common_title">确认收货地址</h3>

    <div class="common_list_con clearfix">
        <dl>
            <dt>寄送到：</dt>
            <dd><input type="radio" name="addr_id" value="{{ addr.id }}" checked="">{{ addr.recipient_addr }} （{{ addr.recipient_name }} 收） {{ addr.recipient_phone }}</dd>
        </dl>
        <a href="{% url 'user:address' %}" class="edit_site">编辑收货地址</a>
{#    "{% url "order:address" %}"   用户中心#}

    </div>

    <h3 class="common_title">支付方式</h3>
    <div class="common_list_con clearfix">
        <div class="pay_style_con clearfix">
            <input type="radio" name="pay_style" value="1" checked>
            <label class="cash">货到付款</label>
            <input type="radio" name="pay_style" value="2">
            <label class="weixin">微信支付</label>
            <input type="radio" name="pay_style" value="3">
            <label class="zhifubao"></label>
            <input type="radio" name="pay_style" value="4">
            <label class="bank">银行卡支付</label>
        </div>
    </div>

    <h3 class="common_title">商品列表</h3>

    <div class="common_list_con clearfix">
        <ul class="book_list_th clearfix">
            <li class="col01">商品名称</li>
            <li class="col02">商品单位</li>
            <li class="col03">商品价格</li>
            <li class="col04">数量</li>
            <li class="col05">小计</li>
        </ul>
        {% for book in books_li %}
        <ul class="books_list_td clearfix">
            <li class="col01">{{ forloop.counter }}</li>
            <li class="col02"><img src="{% static book.image %}"></li>
            <li class="col03">{{ book.name }}</li>
            <li class="col04">{{ book.unite }}</li>
            <li class="col05">{{ book.price }}元</li>
            <li class="col06">{{ book.count }}</li>
            <li class="col07">{{ book.amount }}元</li>
        </ul>
        {% endfor %}
    </div>

    <h3 class="common_title">总金额结算</h3>

    <div class="common_list_con clearfix">
        <div class="settle_con">
            <div class="total_book_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
            <div class="transit">运费：<b>{{ transit_price }}元</b></div>
            <div class="total_pay">实付款：<b>{{ total_pay }}元</b></div>
        </div>
    </div>

    <div class="order_submit clearfix">
{#    {% csrf_token %}#}
        <a href="javascript:;" id="order_btn" books_ids="{{ books_ids }}">提交订单</a>
        {% csrf_token %}
{#    books_ids="{{ books_ids }}"#}
    </div>
{% endblock body %}
{% block bottom %}
    <div class="popup_con">
        <div class="popup">
            <p>订单提交成功！</p>
        </div>

        <div class="mask"></div>
    </div>
{% endblock bottom %}
{% block bottomfiles %}
    <script type="text/javascript">
        $('#order_btn').click(function() {
            addr_id = $('input[name="addr_id"]').val()
            pay_method = $('input[name="pay_style"]:checked').val()
            books_ids = $(this).attr('books_ids')
            csrf = $('input[name="csrfmiddlewaretoken"]').val()

            params = {
                'addr_id':addr_id,
                'pay_method':pay_method,
                'books_ids':books_ids,
                'csrfmiddlewaretoken':csrf
            }

            $.post('/order/commit/',params,function (data) {
                if (data.res == 6) {
                    localStorage.setItem('order_finish', 2);

                    $('.popup_con').fadeIn('fast', function () {

                        setTimeout(function () {
                            $('.popup_con').fadeOut('fast', function () {
                                window.location.href = 'index.html';
                            });
                        }, 3000)
                    })
                }
                else {
                    alert(data.errmsg)
                }
            });
        });
    </script>
{% endblock bottomfiles %}
